name: CI
on: [push,pull_request]
jobs:
  lint:
    name: Golangci-lint
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: Mushus/golangci-linter@v1

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0

  test:
    name: Unit Testing
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Checkout
        uses: actions/checkout@v2

  sync:
    name: Sync Code To Gitee
    runs-on: ubuntu-18.04
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY_LMM }}
        with:
          source-repo: "git@github.com:hyperbench/hyperbench-common.git"
          destination-repo: "git@gitee.com:hyperbench/hyperbench-common.git"